// PRINT WELCOME MESSAGE

// WHILE USER WANT TO PLAY
//    ASK USER NUMBER OF ROUNDS TO PLAY
//    SET VAR rounds FOR ROUNDS TO PLAY WITH USER INPUT
//    SET VAR score FOR SCORE
//    WHILE NOT rounds ROUNDS ARE PLAYED
//      PLAY ROUND BY CALLING playRound() FUNCTION
//    END WHILE
// PRINT score SCORE
// ASK USER TO REPLAY OR QUIT
// IF QUIT
//    BREAK LOOP
// END WHILE
// PRINT QUIT MESSAGE

